### ISSUE TITLE
Unit Project #3

### ISSUE THREAD

**Issue by peacing** [mackenziejane/mackenzie-data-science#3]
Mackensie, some feedback for unit proj 3:

| Score | Requirements                                                                 | Notes                                                                                       |
|-------|------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------|
| 2     | Create one-hot encoding using binary variables                               | Well done.                                                                                  |
| 3     | Calculate odds ratios by hand                                                | All calculations look good! I'm impressed you used only variables and no hardcoded values.  |
| 2     | Complete a logistic regression using statsmodels and interpret your findings | Good job fitting the model and interpretations are spot on!                                 |
| 2     | Calculate predicted probabilities                                            | Predicted probabilities are correct!                                                        |
| 2     | Do a similar analysis using sklearn                                          | Once again, great job! I like that you made a dataframe of sklearn and statmodel's results. |

**Comment by mackenziejane** [comment]
Thank you for grading! Really appreciate it :)
